apiVersion: apps/v1
kind: Deployment
metadata:
  name: read-doc-app
  labels:
    app: read-doc-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: read-doc-app
  template:
    metadata:
      labels:
        app: read-doc-app
    spec:
      containers:
        - name: fastapi-container
          image: your-dockerhub-username/fastapi-app:latest
          ports:
            - containerPort: 8000
          env:
            - name: MODEL_PATH
              value: "/apps/models/local" # ローカルモデルを使用する場合のパス
            - name: CACHE_PATH
              value: "/apps/models/.cache" # ローカルモデルを使用する場合のパス
      #     volumeMounts:
      #       - mountPath: /apps/models
      #         name: model-storage
      # volumes:
      #   - name: model-storage
      #     persistentVolumeClaim:
      #       claimName: model-pvc # ローカルモデルのPVC名を指定
---
apiVersion: v1
kind: Service
metadata:
  name: read-doc-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: read-doc-app
